In [2]:
!pip install yfinance==0.1.67
#!pip install pandas==1.3.3

Requirement already satisfied: yfinance==0.1.67 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (0.1.67)
Requirement already satisfied: pandas>=0.24 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.3.5)
Requirement already satisfied: requests>=2.20 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (2.27.1)
Requirement already satisfied: lxml>=4.5.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (4.9.0)
Requirement already satisfied: multitasking>=0.0.7 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (0.0.10)
Requirement already satisfied: numpy>=1.15 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2022.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2022.5.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2.0.12)
Requirement already satisfied: six>=1.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance==0.1.67) (1.16.0)

In [35]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [17]:
tsla = yf.Ticker("TSLA")

In [18]:
tsla_info=tsla.info
tsla.info

{'zip': '78725',
 'sector': 'Consumer Cyclical',
 'fullTimeEmployees': 99290,
 'longBusinessSummary': 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally. The company operates in two segments, Automotive, and Energy Generation and Storage. The Automotive segment offers electric vehicles, as well as sells automotive regulatory credits. It provides sedans and sport utility vehicles through direct and used vehicle sales, a network of Tesla Superchargers, and in-app upgrades; and purchase financing and leasing services. This segment is also involved in the provision of non-warranty after-sales vehicle services, sale of used vehicles, retail merchandise, and vehicle insurance, as well as sale of products to third party customers; services for electric vehicles through its company-owned service locations, and Tesla mobile service technicians; and vehicle limited warranties and extended service plans. The Energy Generation and Storage segment engages in the design, manufacture, installation, sale, and leasing of solar energy generation and energy storage products, and related services to residential, commercial, and industrial customers and utilities through its website, stores, and galleries, as well as through a network of channel partners. This segment also offers service and repairs to its energy product customers, including under warranty; and various financing options to its solar customers. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was incorporated in 2003 and is headquartered in Austin, Texas.',
 'city': 'Austin',
 'phone': '(512) 516-8177',
 'state': 'TX',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'https://www.tesla.com',
 'maxAge': 1,
 'address1': '13101 Tesla Road',
 'industry': 'Auto Manufacturers',
 'ebitdaMargins': 0.20424,
 'profitMargins': 0.13505,
 'grossMargins': 0.27096,
 'operatingCashflow': 13850999808,
 'revenueGrowth': 0.805,
 'operatingMargins': 0.1549,
 'ebitda': 12702000128,
 'targetLowPrice': 67,
 'recommendationKey': 'buy',
 'grossProfits': 13606000000,
 'freeCashflow': 7054624768,
 'targetMedianPrice': 950,
 'currentPrice': 729.4877,
 'earningsGrowth': 6.315,
 'currentRatio': 1.354,
 'returnOnAssets': 0.10118,
 'numberOfAnalystOpinions': 40,
 'targetMeanPrice': 905.97,
 'debtToEquity': 19.841,
 'returnOnEquity': 0.28261,
 'targetHighPrice': 1620,
 'totalCash': 18012999680,
 'totalDebt': 7024999936,
 'totalRevenue': 62189998080,
 'totalCashPerShare': 17.387,
 'financialCurrency': 'USD',
 'revenuePerShare': 61.927,
 'quickRatio': 0.953,
 'recommendationMean': 2.4,
 'exchange': 'NMS',
 'shortName': 'Tesla, Inc.',
 'longName': 'Tesla, Inc.',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'TSLA',
 'messageBoardId': 'finmb_27444752',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 10.677,
 'beta3Year': None,
 'enterpriseToEbitda': 52.278,
 '52WeekChange': 0.049622655,
 'morningStarRiskRating': None,
 'forwardEps': 15.95,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 1036009984,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 32.901,
 'sharesShort': 27541699,
 'sharesPercentSharesOut': 0.026600001,
 'fundFamily': None,
 'lastFiscalYearEnd': 1640908800,
 'heldPercentInstitutions': 0.43152002,
 'netIncomeToCommon': 8403999744,
 'trailingEps': 7.4,
 'lastDividendValue': None,
 'SandP52WeekChange': -0.11329222,
 'priceToBook': 22.172203,
 'heldPercentInsiders': 0.17263001,
 'nextFiscalYearEnd': 1703980800,
 'yield': None,
 'mostRecentQuarter': 1648684800,
 'shortRatio': 0.89,
 'sharesShortPreviousMonthDate': 1651190400,
 'floatShares': 856832008,
 'beta': 2.132032,
 'enterpriseValue': 664029560832,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1598832000,
 'lastSplitFactor': '5:1',
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 6.575,
 'priceToSalesTrailing12Months': 12.15238,
 'dateShortInterest': 1653955200,
 'pegRatio': 1.36,
 'ytdReturn': None,
 'forwardPE': 45.735905,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0325,
 'sharesShortPriorMonth': 23732107,
 'impliedSharesOutstanding': 0,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 705.21,
 'regularMarketOpen': 712.405,
 'twoHundredDayAverage': 912.24725,
 'trailingAnnualDividendYield': 0,
 'payoutRatio': 0,
 'volume24Hr': None,
 'regularMarketDayHigh': 738.1962,
 'navPrice': None,
 'averageDailyVolume10Day': 34721410,
 'regularMarketPreviousClose': 705.21,
 'fiftyDayAverage': 796.319,
 'trailingAnnualDividendRate': 0,
 'open': 712.405,
 'toCurrency': None,
 'averageVolume10days': 34721410,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 708.26,
 'currency': 'USD',
 'trailingPE': 98.579414,
 'regularMarketVolume': 18991150,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 755756498944,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 28891520,
 'dayLow': 708.26,
 'ask': 729.11,
 'askSize': 1000,
 'volume': 18991150,
 'fiftyTwoWeekHigh': 1243.49,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 620.46,
 'bid': 729.14,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 1100,
 'dayHigh': 738.1962,
 'regularMarketPrice': 729.4877,
 'preMarketPrice': 712.74,
 'logo_url': 'https://logo.clearbit.com/tesla.com'}

In [19]:
tsla_share_price_data = tsla.history(period="max")

In [20]:
tsla_share_price_data.head()

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date
2010-06-29  3.800  5.000  3.508  4.778  93831500          0           0.0
2010-06-30  5.158  6.084  4.660  4.766  85935500          0           0.0
2010-07-01  5.000  5.184  4.054  4.392  41094000          0           0.0
2010-07-02  4.600  4.620  3.742  3.840  25699000          0           0.0
2010-07-06  4.000  4.000  3.166  3.222  34334500          0           0.0

In [21]:
tsla_revenue_data = tsla.history(period="max")

In [22]:
tsla_revenue_data.head()

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date
2010-06-29  3.800  5.000  3.508  4.778  93831500          0           0.0
2010-06-30  5.158  6.084  4.660  4.766  85935500          0           0.0
2010-07-01  5.000  5.184  4.054  4.392  41094000          0           0.0
2010-07-02  4.600  4.620  3.742  3.840  25699000          0           0.0
2010-07-06  4.000  4.000  3.166  3.222  34334500          0           0.0

In [23]:
GME= yf.Ticker("GME")

In [27]:
GME_share_price_data = GME.history(period="max")

In [29]:
GME_share_price_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-02-13,6.480513,6.773399,6.413183,6.766666,19054000,0.0,0.0
2002-02-14,6.850830,6.864296,6.682505,6.733002,2755400,0.0,0.0
2002-02-15,6.733001,6.749833,6.632006,6.699336,2097400,0.0,0.0
2002-02-19,6.665672,6.665672,6.312190,6.430017,1852600,0.0,0.0
2002-02-20,6.463681,6.648838,6.413183,6.648838,1723200,0.0,0.0

In [33]:
GME_revenue_data = GME.history(period="max")

In [34]:
GME_revenue_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-02-13,6.480513,6.773399,6.413183,6.766666,19054000,0.0,0.0
2002-02-14,6.850830,6.864296,6.682505,6.733002,2755400,0.0,0.0
2002-02-15,6.733003,6.749835,6.632008,6.699337,2097400,0.0,0.0
2002-02-19,6.665671,6.665671,6.312189,6.430017,1852600,0.0,0.0
2002-02-20,6.463682,6.648839,6.413184,6.648839,1723200,0.0,0.0